# permissions for end users to edit nginxoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginxoperator-editor-role
rules:
- apiGroups:
  - operator.fii.org
  resources:
  - nginxoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.fii.org
  resources:
  - nginxoperators/status
  verbs:
  - get
